# -*- mode: makefile-gmake -*-

ADDITIONAL_INCLUDE_DIRS += -I../..
ADDITIONAL_GUI_LIBS += -lDesktopKit -lSystemKit -ldispatch

ifeq ($(findstring freebsd,$(GNUSTEP_TARGET_OS)),freebsd)
  ADDITIONAL_CPPFLAGS += -I/usr/local/NextSpace/include
  ADDITIONAL_LDFLAGS  += -L/usr/local/NextSpace/lib
endif
